# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'GZHTTPConnectionDemo' do

end

target 'GZHTTPConnectionDemoTests' do

end

target 'GZNetwork' do
    
pod 'Reachability'

end

target 'GZNetworkTests' do

end

